/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'PayMateReputation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PayMateReputation__factory>
getContractFactory(name: 'PayMateTreasury', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PayMateTreasury__factory>
getContractFactory(name: 'YieldEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.YieldEscrow__factory>
getContractFactory(name: 'TestUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TestUSDC__factory>

  getContractAt(name: 'PayMateReputation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PayMateReputation>
getContractAt(name: 'PayMateTreasury', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PayMateTreasury>
getContractAt(name: 'YieldEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.YieldEscrow>
getContractAt(name: 'TestUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TestUSDC>

  deployContract(name: 'PayMateReputation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PayMateReputation>
deployContract(name: 'PayMateTreasury', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PayMateTreasury>
deployContract(name: 'YieldEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.YieldEscrow>
deployContract(name: 'TestUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestUSDC>

  deployContract(name: 'PayMateReputation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PayMateReputation>
deployContract(name: 'PayMateTreasury', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PayMateTreasury>
deployContract(name: 'YieldEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.YieldEscrow>
deployContract(name: 'TestUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TestUSDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  