/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PayMateReputation {
      
    export type RepStruct = {jobsCompleted: BigNumberish, totalEarnedUsd: BigNumberish, score: BigNumberish}

    export type RepStructOutput = [jobsCompleted: bigint, totalEarnedUsd: bigint, score: bigint] & {jobsCompleted: bigint, totalEarnedUsd: bigint, score: bigint }
  
    }

  export interface PayMateReputationInterface extends Interface {
    getFunction(nameOrSignature: "getReputation" | "issuer" | "recordJob" | "reputation"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "JobRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'getReputation', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'issuer', values?: undefined): string;
encodeFunctionData(functionFragment: 'recordJob', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'reputation', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'getReputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'issuer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputation', data: BytesLike): Result;
  }

  
    export namespace JobRecordedEvent {
      export type InputTuple = [freelancer: AddressLike, amountUsd: BigNumberish, newScore: BigNumberish];
      export type OutputTuple = [freelancer: string, amountUsd: bigint, newScore: bigint];
      export interface OutputObject {freelancer: string, amountUsd: bigint, newScore: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PayMateReputation extends BaseContract {
    
    connect(runner?: ContractRunner | null): PayMateReputation;
    waitForDeployment(): Promise<this>;

    interface: PayMateReputationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getReputation: TypedContractMethod<
      [freelancer: AddressLike, ],
      [PayMateReputation.RepStructOutput],
      'view'
    >
    

    
    issuer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    recordJob: TypedContractMethod<
      [freelancer: AddressLike, amountUsd: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reputation: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {jobsCompleted: bigint, totalEarnedUsd: bigint, score: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getReputation'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [PayMateReputation.RepStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'issuer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'recordJob'): TypedContractMethod<
      [freelancer: AddressLike, amountUsd: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputation'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {jobsCompleted: bigint, totalEarnedUsd: bigint, score: bigint }],
      'view'
    >;

    getEvent(key: 'JobRecorded'): TypedContractEvent<JobRecordedEvent.InputTuple, JobRecordedEvent.OutputTuple, JobRecordedEvent.OutputObject>;

    filters: {
      
      'JobRecorded(address,uint256,uint256)': TypedContractEvent<JobRecordedEvent.InputTuple, JobRecordedEvent.OutputTuple, JobRecordedEvent.OutputObject>;
      JobRecorded: TypedContractEvent<JobRecordedEvent.InputTuple, JobRecordedEvent.OutputTuple, JobRecordedEvent.OutputObject>;
    
    };
  }