/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace YieldEscrow {
      
    export type InvoiceEscrowStruct = {client: AddressLike, freelancer: AddressLike, principalAmount: BigNumberish, maturesAt: BigNumberish, funded: boolean, isResolved: boolean}

    export type InvoiceEscrowStructOutput = [client: string, freelancer: string, principalAmount: bigint, maturesAt: bigint, funded: boolean, isResolved: boolean] & {client: string, freelancer: string, principalAmount: bigint, maturesAt: bigint, funded: boolean, isResolved: boolean }
  
    }

  export interface YieldEscrowInterface extends Interface {
    getFunction(nameOrSignature: "confirmFunded" | "escrows" | "getEscrow" | "owner" | "registerInvoice" | "renounceOwnership" | "resolveDispute" | "resolveEscrow" | "transferOwnership" | "usdcToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeResolved" | "EscrowFunded" | "EscrowResolved" | "InvoiceRegistered" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'confirmFunded', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrows', values: [string]): string;
encodeFunctionData(functionFragment: 'getEscrow', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerInvoice', values: [string, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveEscrow', values: [string]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'confirmFunded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerInvoice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
  }

  
    export namespace DisputeResolvedEvent {
      export type InputTuple = [invoiceId: string, resolution: BigNumberish, freelancer: AddressLike, client: AddressLike, amount: BigNumberish];
      export type OutputTuple = [invoiceId: string, resolution: bigint, freelancer: string, client: string, amount: bigint];
      export interface OutputObject {invoiceId: string, resolution: bigint, freelancer: string, client: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowFundedEvent {
      export type InputTuple = [invoiceId: string, funder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [invoiceId: string, funder: string, amount: bigint];
      export interface OutputObject {invoiceId: string, funder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowResolvedEvent {
      export type InputTuple = [invoiceId: string, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [invoiceId: string, recipient: string, amount: bigint];
      export interface OutputObject {invoiceId: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvoiceRegisteredEvent {
      export type InputTuple = [invoiceId: string, client: AddressLike, freelancer: AddressLike, maturesAt: BigNumberish];
      export type OutputTuple = [invoiceId: string, client: string, freelancer: string, maturesAt: bigint];
      export interface OutputObject {invoiceId: string, client: string, freelancer: string, maturesAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface YieldEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): YieldEscrow;
    waitForDeployment(): Promise<this>;

    interface: YieldEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    confirmFunded: TypedContractMethod<
      [invoiceId: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: string, ],
      [[string, string, bigint, bigint, boolean, boolean] & {client: string, freelancer: string, principalAmount: bigint, maturesAt: bigint, funded: boolean, isResolved: boolean }],
      'view'
    >
    

    
    getEscrow: TypedContractMethod<
      [invoiceId: string, ],
      [YieldEscrow.InvoiceEscrowStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerInvoice: TypedContractMethod<
      [invoiceId: string, client: AddressLike, freelancer: AddressLike, maturesAt: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [invoiceId: string, resolution: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveEscrow: TypedContractMethod<
      [invoiceId: string, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'confirmFunded'): TypedContractMethod<
      [invoiceId: string, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, bigint, bigint, boolean, boolean] & {client: string, freelancer: string, principalAmount: bigint, maturesAt: bigint, funded: boolean, isResolved: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrow'): TypedContractMethod<
      [invoiceId: string, ],
      [YieldEscrow.InvoiceEscrowStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerInvoice'): TypedContractMethod<
      [invoiceId: string, client: AddressLike, freelancer: AddressLike, maturesAt: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [invoiceId: string, resolution: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveEscrow'): TypedContractMethod<
      [invoiceId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'EscrowFunded'): TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
getEvent(key: 'EscrowResolved'): TypedContractEvent<EscrowResolvedEvent.InputTuple, EscrowResolvedEvent.OutputTuple, EscrowResolvedEvent.OutputObject>;
getEvent(key: 'InvoiceRegistered'): TypedContractEvent<InvoiceRegisteredEvent.InputTuple, InvoiceRegisteredEvent.OutputTuple, InvoiceRegisteredEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'DisputeResolved(string,uint8,address,address,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'EscrowFunded(string,address,uint256)': TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
      EscrowFunded: TypedContractEvent<EscrowFundedEvent.InputTuple, EscrowFundedEvent.OutputTuple, EscrowFundedEvent.OutputObject>;
    

      'EscrowResolved(string,address,uint256)': TypedContractEvent<EscrowResolvedEvent.InputTuple, EscrowResolvedEvent.OutputTuple, EscrowResolvedEvent.OutputObject>;
      EscrowResolved: TypedContractEvent<EscrowResolvedEvent.InputTuple, EscrowResolvedEvent.OutputTuple, EscrowResolvedEvent.OutputObject>;
    

      'InvoiceRegistered(string,address,address,uint256)': TypedContractEvent<InvoiceRegisteredEvent.InputTuple, InvoiceRegisteredEvent.OutputTuple, InvoiceRegisteredEvent.OutputObject>;
      InvoiceRegistered: TypedContractEvent<InvoiceRegisteredEvent.InputTuple, InvoiceRegisteredEvent.OutputTuple, InvoiceRegisteredEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }