"use client"

import Link from "next/link"
import { useMemo, useState } from "react"
import { Icon } from "@/components/icons"

const sections = [
  { id: "overview", label: "Project overview" },
  { id: "architecture", label: "Architecture" },
  { id: "setup", label: "Local setup" },
  { id: "environment", label: "Environment" },
  { id: "api", label: "API routes" },
  { id: "frontend", label: "Frontend routes" },
  { id: "contract", label: "Reputation contract" },
  { id: "deploy", label: "Deployment" },
]

export default function DocsPage(){
 const [query,setQuery]=useState("")
 const visible=useMemo(()=>sections.filter(s=>s.label.toLowerCase().includes(query.toLowerCase())),[query])
 return <main className="docs-shell">
  <header className="docs-header"><Link href="/" className="brand"><span className="brand-mark"><span/></span><b>PayMate</b></Link><span className="docs-slash">/</span><b>PROJECT DOCS</b><div className="docs-search"><Icon name="spark" size={15}/><input aria-label="Filter project documentation" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find project details…"/><kbd>⌘ K</kbd></div><Link href="/dashboard" className="docs-launch">Open app <Icon name="arrow" size={16}/></Link></header>
  <aside className="docs-sidebar"><div className="docs-version"><i/>PayMate v2.0</div><nav><span>PROJECT</span>{visible.slice(0,2).map(s=><a key={s.id} href={`#${s.id}`}>{s.label}</a>)}<span>RUN</span>{visible.slice(2,4).map(s=><a key={s.id} href={`#${s.id}`}>{s.label}</a>)}<span>REFERENCE</span>{visible.slice(4).map(s=><a key={s.id} href={`#${s.id}`}>{s.label}</a>)}</nav><div className="docs-side-foot"><Link href="/">← Landing page</Link><Link href="/dashboard">Open workspace</Link></div></aside>
  <article className="docs-content project-docs">
   <div className="docs-breadcrumb">PAYMATE <span>/</span> PROJECT DETAILS</div>
   <section className="docs-hero project-docs-hero" id="overview"><div className="docs-kicker"><span>PROJECT DOCUMENTATION</span><i>V2.0</i></div><h1>PayMate project.</h1><p>A full-stack Web3 invoicing application for creating USDC payment links, verifying settlement on GOAT Testnet3, and recording freelancer reputation on-chain.</p><div className="project-facts"><div><span>FRONTEND</span><b>Next.js 16</b></div><div><span>API</span><b>Next.js route handlers</b></div><div><span>NETWORK</span><b>GOAT Testnet3</b></div><div><span>STORAGE</span><b>SQLite</b></div></div></section>
   <section className="doc-section" id="architecture"><div className="doc-index">01</div><div><span className="doc-label">ARCHITECTURE</span><h2>Project structure</h2><p>The repository contains two independent parts that work together.</p><div className="project-tree"><div><code>web/</code><span>Next.js landing page, dashboard, docs, payment checkout, and the <code>/api/*</code> invoice, settlement, and reputation routes</span></div><div><code>contracts/</code><span>Hardhat project containing the PayMate reputation registry</span></div></div><div className="flow-diagram"><div><span>1</span><b>Next.js client</b><small>Creates and displays invoices</small></div><i/><div><span>2</span><b>Next.js route handlers</b><small>Store and verify settlement</small></div><i/><div><span>3</span><b>GOAT contracts</b><small>USDC and reputation records</small></div></div></div></section>
   <section className="doc-section" id="setup"><div className="doc-index">02</div><div><span className="doc-label">LOCAL SETUP</span><h2>Run the project</h2><ol className="doc-steps"><li><b>Install and run</b><pre><code>cd web{`\n`}npm install{`\n`}npm run dev</code></pre></li><li><b>Open the application</b><p>Visit <code>http://localhost:3000</code>. The API health endpoint is <code>http://localhost:3000/api/health</code>.</p></li></ol></div></section>
   <section className="doc-section" id="environment"><div className="doc-index">03</div><div><span className="doc-label">ENVIRONMENT</span><h2>Required configuration</h2><p>Copy <code>web/.env.example</code> to <code>web/.env.local</code> and set the deployment-specific values.</p><div className="property-table"><div><b>Variable</b><b>Purpose</b></div><div><code>OPENAI_API_KEY</code><span>Optional intelligent drafting</span></div><div><code>OPENAI_MODEL</code><span>Drafting model name</span></div><div><code>RPC_GOAT_TESTNET</code><span>GOAT Testnet3 RPC</span></div><div><code>USDC_TOKEN</code><span>Settlement token address</span></div><div><code>REPUTATION_CONTRACT</code><span>Deployed registry address</span></div><div><code>PRIVATE_KEY</code><span>Authorized reputation issuer</span></div><div><code>PAYMATE_DB_PATH</code><span>SQLite database path (defaults to <code>web/paymate.db</code>)</span></div></div></div></section>
   <section className="doc-section" id="api"><div className="doc-index">04</div><div><span className="doc-label">API ROUTES</span><h2>Backend endpoints</h2><div className="route-table"><div><b>GET</b><code>/api/health</code><span>Service health</span></div><div><b>POST</b><code>/api/invoices/draft</code><span>Generate a reviewable intelligent draft</span></div><div><b>POST</b><code>/api/invoices</code><span>Create an approved invoice</span></div><div><b>GET</b><code>/api/invoices?freelancer=0x…</code><span>List wallet invoices</span></div><div><b>GET</b><code>/api/invoices/{`{id}`}</code><span>Load one invoice</span></div><div><b>POST</b><code>/api/pay/{`{id}`}/settle</code><span>Get 402 requirements or verify payment</span></div><div><b>GET</b><code>/api/reputation/{`{address}`}</code><span>Read reputation data</span></div></div><div className="doc-callout"><Icon name="shield"/><div><b>Settlement verification</b><p>The API checks transaction success, USDC token address, recipient wallet, and transferred amount before marking an invoice paid.</p></div></div></div></section>
   <section className="doc-section" id="frontend"><div className="doc-index">05</div><div><span className="doc-label">FRONTEND ROUTES</span><h2>Application pages</h2><div className="route-table frontend-routes"><div><b>PAGE</b><code>/</code><span>Product landing page</span></div><div><b>PAGE</b><code>/dashboard</code><span>Invoice and reputation workspace</span></div><div><b>PAGE</b><code>/pay/{`{invoice-id}`}</code><span>Client wallet checkout</span></div><div><b>PAGE</b><code>/docs</code><span>Project documentation</span></div></div></div></section>
   <section className="doc-section" id="contract"><div className="doc-index">06</div><div><span className="doc-label">REPUTATION CONTRACT</span><h2>PayMateReputation.sol</h2><p>The issuer records a completed job only after verified payment. Anyone can read a freelancer’s completed jobs, total settled value, and score.</p><pre><code>{`recordJob(address freelancer, uint256 amountUsd)\ngetReputation(address freelancer) returns (Rep)`}</code></pre><p>Deploy from the <code>contracts/</code> directory with the configured GOAT Testnet3 RPC and issuer key.</p></div></section>
   <section className="doc-section" id="deploy"><div className="doc-index">07</div><div><span className="doc-label">DEPLOYMENT</span><h2>Production checklist</h2><ul className="deploy-list"><li><Icon name="check"/>Deploy the reputation contract and save its address.</li><li><Icon name="check"/>Set the correct GOAT Testnet3 USDC token address.</li><li><Icon name="check"/>Use a persistent database path and protected issuer key.</li><li><Icon name="check"/>Run <code>npm run build</code> then <code>npm run start</code> behind HTTPS.</li></ul></div></section>
   <footer className="docs-footer"><div><span className="brand-mark small"><span/></span><b>PayMate project documentation</b></div><Link href="/dashboard">Open workspace <Icon name="arrow"/></Link></footer>
  </article>
  <aside className="docs-toc"><span>PROJECT DETAILS</span>{sections.map(s=><a key={s.id} href={`#${s.id}`}>{s.label}</a>)}<div className="toc-status"><i/><b>GOAT Testnet3</b><small>Configured through environment</small></div></aside>
 </main>
}
