"use client"
import Link from "next/link"
import { useEffect, useRef, useState } from "react"
import { useAccount } from "wagmi"
import { usePrivy } from "@privy-io/react-auth"
import { isAddress } from "viem"
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query"
import { Icon } from "@/components/icons"
import { WalletConnectMenu } from "@/components/wallet-connect-menu"
import { FeedbackForm } from "@/components/feedback-form"

type Reputation={jobsCompleted:number;totalEarnedUsd:number;score:number}
type Invoice={id:string;title:string;description:string;client:string;txHash:string|null;amountUsd:number;status:"pending"|"paid"|"cancelled";payUrl?:string;createdAt:number;dueDate?:string}

export default function DashboardPage(){
 const {address,isConnected}=useAccount();const {logout}=usePrivy()
 const queryClient=useQueryClient()
 const [client,setClient]=useState("");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [amount,setAmount]=useState("");const [dueDate,setDueDate]=useState("")
 const [draftPrompt,setDraftPrompt]=useState("");const [draftMeta,setDraftMeta]=useState<{source:string;confidence:number;paymentTerms?:string}|null>(null)
 const [formError,setFormError]=useState<string|null>(null);const [copied,setCopied]=useState<string|null>(null)
 const [search,setSearch]=useState("");const searchRef=useRef<HTMLInputElement>(null)
 useEffect(()=>{function onKey(e:KeyboardEvent){if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();searchRef.current?.focus()}}window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[])
 const invoicesQuery=useQuery({queryKey:["invoices",address],enabled:isConnected&&!!address,queryFn:async()=>{const res=await fetch(`/api/invoices?freelancer=${address}`);if(!res.ok)throw new Error("Could not reach the PayMate API.");return (await res.json()).invoices as Invoice[]}})
 const reputationQuery=useQuery({queryKey:["reputation",address],enabled:isConnected&&!!address,queryFn:async()=>{const res=await fetch(`/api/reputation/${address}`);if(!res.ok)throw new Error("Could not reach the PayMate API.");return (await res.json()) as Reputation}})
 const invoices=invoicesQuery.data??[];const reputation=reputationQuery.data??null
 const error=formError??((invoicesQuery.isError||reputationQuery.isError)?"Could not reach the PayMate API.":null)
 const draftMutation=useMutation({mutationFn:async(prompt:string)=>{const res=await fetch(`/api/invoices/draft`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Draft generation failed");return data.draft},onSuccess:(draft)=>{setTitle(draft.title||"");setDescription(draft.description||draftPrompt);setAmount(draft.amountUsd?String(draft.amountUsd):"");setDueDate(draft.dueDate||"");setDraftMeta({source:draft.source||"ai",confidence:Number(draft.confidence||0),paymentTerms:draft.paymentTerms});setFormError(null)},onError:(e)=>setFormError(e instanceof Error?e.message:"Could not generate draft")})
 const createInvoiceMutation=useMutation({mutationFn:async()=>{const res=await fetch(`/api/invoices`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({freelancer:address,client,title,description,amountUsd:Number(amount),dueDate:dueDate||null})});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Invoice creation failed");return {...data.invoice,payUrl:`${location.origin}${data.payUrl}`} as Invoice},onSuccess:(created)=>{queryClient.setQueryData<Invoice[]>(["invoices",address],(prev)=>[created,...(prev??[])]);setClient("");setTitle("");setDescription("");setAmount("");setDueDate("");setFormError(null)},onError:(e)=>setFormError(e instanceof Error?e.message:"Could not create invoice")})
 const cancelInvoiceMutation=useMutation({mutationFn:async(id:string)=>{const res=await fetch(`/api/invoices/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status:"cancelled",freelancer:address})});const data=await res.json();if(!res.ok)throw new Error(data.detail||"Cancel failed");return data},onSuccess:(updated)=>{queryClient.setQueryData<Invoice[]>(["invoices",address],(prev)=>(prev??[]).map(i=>i.id===updated.id?updated:i));},onError:(e)=>setFormError(e instanceof Error?e.message:"Could not cancel invoice")})
 function generateDraft(){if(draftPrompt.trim().length<12)return setFormError("Describe the work, price, and any deadline in a little more detail.");draftMutation.mutate(draftPrompt)}
 function createInvoice(e:React.FormEvent){e.preventDefault();if(!address)return setFormError("Connect your wallet first.");if(!isAddress(client))return setFormError("Enter a valid client wallet address.");if(!title.trim()||description.trim().length<5||!amount||Number(amount)<=0)return setFormError("Complete the title, work description, and amount.");createInvoiceMutation.mutate()}
 async function copyInvoice(inv:Invoice){const url=`${location.origin}/pay/${inv.id}`;await navigator.clipboard.writeText(url);setCopied(inv.id);setTimeout(()=>setCopied(null),1500)}
 const paid=invoices.filter(i=>i.status==="paid");const outstanding=invoices.filter(i=>i.status==="pending").reduce((s,i)=>s+i.amountUsd,0);const maxInvoice=Math.max(1,...invoices.slice(0,7).map(i=>i.amountUsd));const settlementRate=invoices.length?Math.round((paid.length/invoices.length)*100):0
 const q=search.trim().toLowerCase();const filteredInvoices=q?invoices.filter(inv=>[inv.title,inv.id,inv.client,inv.txHash].some(f=>f?.toLowerCase().includes(q))):invoices
 return <main className="app-shell"><div className="app-frame"><aside className="app-sidebar"><Link className="brand" href="/"><span className="brand-mark"><span/></span><b>PayMate</b></Link><nav className="side-nav"><span className="nav-label">WORKSPACE</span><Link className="active" href="/dashboard"><Icon name="chart"/><span>Overview</span></Link><a href="#new"><Icon name="invoice"/><span>New invoice</span></a><a href="#activity"><Icon name="users"/><span>Activity</span></a><span className="nav-label">IDENTITY</span><a href="#reputation"><Icon name="shield"/><span>Reputation</span></a><a href="#feedback"><Icon name="send"/><span>Feedback</span></a></nav><div className="sidebar-foot"><div className="network-chip"><i/><span>GOAT Testnet3 · Live</span></div></div></aside>
 <section className="app-main"><header className="app-topbar"><div><span className="workspace-label">PAYMATE CONTROL CENTER</span><h1>Money, proof, momentum.</h1><p>Create invoices and track verified settlement from one workspace.</p></div><div className="topbar-actions"><Link href="/docs" className="topbar-icon"><Icon name="invoice" size={17}/></Link>{isConnected?<button className="wallet-button" onClick={()=>logout()}><span className="live-dot"/>{address?.slice(0,6)}…{address?.slice(-4)}</button>:<WalletConnectMenu triggerClassName="wallet-button primary" triggerLabel={<><Icon name="wallet" size={17}/>Connect wallet</>}/>}</div></header><div className="workspace-toolbar"><div className="toolbar-search"><Icon name="spark" size={15}/><input ref={searchRef} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search invoices, clients, or transaction hashes"/><kbd>⌘ K</kbd></div><div className="toolbar-status"><span><i/>API ONLINE</span><span><i/>GOAT LIVE</span></div><a href="#new" className="toolbar-create"><Icon name="invoice" size={15}/>New invoice</a></div><div className="dashboard-journey"><div className="journey-progress"/><span className="active"><i>1</i><b>Draft</b><small>Structure the work</small></span><em>→</em><span><i>2</i><b>Review</b><small>Approve every detail</small></span><em>→</em><span><i>3</i><b>Share</b><small>Send one link</small></span><em>→</em><span><i>4</i><b>Verify</b><small>Settle on GOAT</small></span></div>
 {!isConnected?<section className="panel connect-empty"><div><div className="empty-orb"><Icon name="wallet" size={34}/></div><h2>Connect once. Run the whole workflow.</h2><p>Your wallet is your identity, payment destination, and portable reputation profile.</p><WalletConnectMenu triggerClassName="button button-primary" triggerLabel={<>Connect Web3 wallet <Icon name="arrow"/></>}/></div></section>:<><div className="metric-grid"><div className="metric-card"><span>Outstanding</span><b>${outstanding.toLocaleString()}</b><small>{invoices.filter(i=>i.status==="pending").length} open invoices</small></div><div className="metric-card"><span>Collected</span><b>${paid.reduce((s,i)=>s+i.amountUsd,0).toLocaleString()}</b><small>{paid.length} verified settlements</small></div><div className="metric-card"><span>Trust score</span><b>{reputation?.score??0}</b><small>ERC-8004 reputation</small></div></div><section className="dashboard-insights panel"><div className="insight-copy"><span className="insight-label">SETTLEMENT PULSE</span><h2>{settlementRate}% <small>verified</small></h2><p>{paid.length} of {invoices.length} invoices have reached final settlement.</p><div className="insight-legend"><span><i className="paid"/>Paid</span><span><i/>Pending</span></div></div><div className="mini-chart" aria-label="Recent invoice values">{invoices.length?invoices.slice(0,7).reverse().map(inv=><div key={inv.id} className={inv.status}><i style={{height:`${Math.max(14,(inv.amountUsd/maxInvoice)*100)}%`}}/><span>${Math.round(inv.amountUsd)}</span></div>):[32,58,45,72,52,86,68].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>—</span></div>)}</div><div className="insight-action"><Icon name="bolt"/><div><b>Live verification</b><span>Every receipt checked on GOAT</span></div><a href="/docs">View protocol <Icon name="arrow" size={14}/></a></div></section><div className="dashboard-grid">
 <div><section className="panel panel-pad" id="new"><div className="panel-heading"><div><h2>Create a verified invoice</h2><p>Clear terms, direct payment, permanent proof.</p></div><span className="icon-box"><Icon name="spark"/></span></div><div className="smart-drafter"><div className="smart-drafter-head"><div><span><Icon name="spark" size={15}/>INTELLIGENT DRAFTING</span><p>Describe the work naturally. PayMate structures a reviewable invoice.</p></div>{draftMeta&&<small className="draft-confidence"><i/>{draftMeta.source==="ai"?"AI structured":"Safe parser"} · {Math.round(draftMeta.confidence*100)}%</small>}</div><div className="smart-drafter-input"><textarea value={draftPrompt} onChange={e=>setDraftPrompt(e.target.value)} placeholder="Example: Brand strategy and visual identity for Northstar, including two workshops and launch assets. Total agreed: $2,480 USDC, due 2026-08-01."/><button type="button" onClick={generateDraft} disabled={draftMutation.isPending}>{draftMutation.isPending?<><span className="draft-spinner"/>Structuring…</>:<><Icon name="spark" size={16}/>Generate draft</>}</button></div>{draftMeta&&<div className="draft-review-note"><Icon name="shield" size={14}/><span>Draft filled below. Review the amount and terms before creating the payment link.</span>{draftMeta.paymentTerms&&<b>{draftMeta.paymentTerms}</b>}</div>}</div><form onSubmit={createInvoice}><div className="form-grid"><div className="field"><label>Client wallet</label><input value={client} onChange={e=>setClient(e.target.value)} placeholder="0x..."/></div><div className="field"><label>Project title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Brand system sprint"/></div><div className="field"><label>Amount · USDC</label><input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="2480.00"/></div><div className="field"><label>Due date</label><input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></div><div className="field full"><label>Scope delivered</label><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the completed work, included deliverables, and agreed terms."/></div></div>{error&&<div className="error-box">{error}</div>}<div className="composer-footer"><span className="hint"><Icon name="shield" size={15}/>Payment goes directly to your wallet.</span><button className="button button-primary" disabled={createInvoiceMutation.isPending}>{createInvoiceMutation.isPending?"Creating…":"Create payment link"}<Icon name="arrow" size={17}/></button></div></form></section>
 <section className="panel activity-panel" id="activity"><div className="panel-heading"><div><h2>Invoice activity</h2><p>Live status from creation to verified settlement.</p></div><span className="activity-count">{filteredInvoices.length}</span></div>{invoices.length===0?<div className="activity-empty">Your first invoice will appear here.</div>:filteredInvoices.length===0?<div className="activity-empty">No invoices match &quot;{search}&quot;.</div>:<div className="invoice-table">{filteredInvoices.map(inv=><div className="invoice-row" key={inv.id}><span className={`status-dot ${inv.status}`}/><div className="invoice-row-main"><b>{inv.title}</b><small>{new Date(inv.createdAt).toLocaleDateString()} · {inv.id.slice(0,8)}</small></div><strong>${inv.amountUsd.toLocaleString()}</strong><span className={`status-label ${inv.status}`}>{inv.status}</span>{inv.status==="pending"&&<button onClick={()=>cancelInvoiceMutation.mutate(inv.id)} aria-label="Cancel invoice"><Icon name="close" size={16}/></button>}<button onClick={()=>copyInvoice(inv)} aria-label="Copy payment link"><Icon name={copied===inv.id?"check":"copy"} size={16}/></button></div>)}</div>}</section></div>
 <aside className="stat-stack" id="reputation"><section className="panel score-panel"><div className="panel-heading"><div><h2>Portable trust</h2><p>ERC-8004 credential</p></div><Icon name="shield"/></div><div className="score-ring"><div><strong>{reputation?.score??0}</strong><small>TRUST SCORE</small></div></div><div className="stat-row"><div className="mini-stat"><span>Jobs verified</span><b>{reputation?.jobsCompleted??0}</b></div><div className="mini-stat"><span>Total settled</span><b>${((reputation?.totalEarnedUsd??0)/1000).toFixed(1)}k</b></div></div></section><section className="panel panel-pad feature-list"><h2>Built into every link</h2><p><Icon name="lock"/>Direct, non-custodial payment</p><p><Icon name="network"/>On-chain transaction verification</p><p><Icon name="shield"/>Automatic reputation recording</p></section><div id="feedback"><FeedbackForm role="freelancer"/></div></aside></div></>}</section></div></main>
}
